### ISSUE TITLE
.tcr replay parsing issue - "Corrupted replay: actions nPlayer > 9"

### ISSUE THREAD

**Issue by Alexander-Parker** [TorchCraft/StarData#11]
I am having an issue parsing the data with the python replayer module. I am able to parse the file linked in a previous issue about parsing (https://www.dropbox.com/s/xow9cfg9r0rheuy/bwrep_00r3w.tcr?dl=0), but am not able to parse any of the files contained in the 20 chunked replay tar.gzs. I am getting the following exception for file I try to parse: 
```
Corrupted replay: actions nPlayer > 9
```

**Comment by ebetica** [comment]
Are you sure you're on the commit in the README? https://github.com/TorchCraft/TorchCraft/commit/a28b153ff10e1826f531d407f723c5e0ccbd488b
