### ISSUE TITLE
May you provide a BT seed please?

### ISSUE THREAD

**Issue by FadeOrigin** [TorchCraft/StarData#2]
Thank you for sharing this precious data!
But due to our restricted network, it's hard to download this dataset from china.

I really wish you can provide a seed, so I can download it through BT.

Thank you again!

**Comment by syhw** [comment]
Can you get it through http from there: http://stardata.s3.amazonaws.com/ ?

**Comment by ebetica** [comment]
Amazon AWS allows us to download files as torrents as long as they are below 5 GB. I split the entire repo into 100+ files, I think you'll have to torrent them all individually I hope that's not too big a burden:

Get the torrents here:
```
https://s3-us-west-2.amazonaws.com/stardata/torrent/stardata.tar.gz.aa?torrent
https://s3-us-west-2.amazonaws.com/stardata/torrent/stardata.tar.gz.ab?torrent
https://s3-us-west-2.amazonaws.com/stardata/torrent/stardata.tar.gz.ac?torrent
...
https://s3-us-west-2.amazonaws.com/stardata/torrent/stardata.tar.gz.dk?torrent
```

It goes from `aa` to `dk`. 

Then, extract the whole archive with `cat stardata.tar.gz.* | tar xzvf -`

I hope this is not too much trouble!

FYI: According to Amazon, the first time the torrent link is requested it may take a couple minutes to serve. I tried `.aa` and it indeed took a while. Please be patient, and probably do it in a script.
