### ISSUE TITLE
What data is saved

### ISSUE THREAD

**Issue by michalsustr** [TorchCraft/StarData#4]
I went through the sources codes to try to find how exactly the data is saved, so I suspect it's somewhere around here:

https://github.com/TorchCraft/StarData/blob/master/extract_units.cpp#L81

I see it saves unit position and type into the output stream.

But that does not match what is written in the whitepaper:

> The saved frame data contains full game state, including unit dynamic characteristics (about 30 per unit) and bullets.

https://arxiv.org/pdf/1708.02139.pdf

Am I missing something?

**Comment by ebetica** [comment]
The actual serialization takes place in torchcraft/replayer, the output stream overloads of frame.h might be useful to you

**Comment by ebetica** [comment]
Closing, feel free to reopen/start a new issue if  you still have questions.
