### ISSUE TITLE
fatal error: 'TH/TH.h' file not found

### ISSUE THREAD

**Issue by lefthandwriter** [TorchCraft/StarData#5]
Hi, when trying to install, I get this error:

```
In file included from py/pyreplayer.cpp:4:
    include/replayer.h:13:10: fatal error: 'TH/TH.h' file not found
    #include <TH/TH.h>
```

It seems the TH.h file is missing from the folder?

The sequence of commands I ran to install:
git clone https://github.com/TorchCraft/StarData
git submodule update --init
cd TorchCraft
pip install .

Would appreciate any help!

**Comment by ebetica** [comment]
Please install this: http://torch.ch.

**Comment by lefthandwriter** [comment]
Thanks that solved it.
