### ISSUE TITLE
Connect to State in a Replay

### ISSUE THREAD

**Issue by andrewsilva9** [TorchCraft/StarData#7]
Hello!

The [python example](https://github.com/TorchCraft/TorchCraft/blob/90e3b9b12ece9fb7c5cbcc0e08a1e525a48a160d/examples/py/example.py) looks very helpful for connecting to a State and gathering relevant information if I have a functional client and I'm stepping through a game, but is there a way to do this when iterating through replays? Can I initialize a State object in the first frame of a Replay somehow, and then step through the replay with that?

Thanks! (and sorry for contributing so many issues to the project)

**Comment by ebetica** [comment]
Yes, it works exactly the same way, except that you cannot send actions.

Sorry about the late reply

**Comment by andrewsilva9** [comment]
Is it possible to use a State or Client without an actual functioning game client? It seems Client requires a connection to a hostname / port, which indicates an active game client?

**Comment by ebetica** [comment]
No there isn't, the starcraft replay files are simply a list of commands issued in the game, and require a game simulator. However, there is an existing C++ StarCraft client:

https://github.com/TorchCraft/TorchCraft/blob/master/docs/user/openbw.md

**Comment by andrewsilva9** [comment]
Great, thanks!
